FROM golang:1.19.3-alpine3.16

RUN apk update
RUN apk add git build-base openssh bash

WORKDIR /app
COPY . .

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0
RUN go install github.com/golang/mock/mockgen@v1.6.0
RUN go install github.com/joho/godotenv/cmd/godotenv@v1.4.0
RUN apk add protoc=3.18.1-r3 protobuf-dev=3.18.1-r3
