FROM golang:1.19.3-alpine3.16 as builder

RUN apk update
RUN apk add git openssh

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
RUN go install github.com/joho/godotenv/cmd/godotenv@v1.4.0
RUN go install github.com/go-delve/delve/cmd/dlv@latest

FROM golang:1.19.3-alpine3.16

RUN apk update
RUN apk add build-base

COPY --from=builder /go /go

WORKDIR /app

COPY . .

RUN GOOS=linux go build -gcflags='all=-N -l' -tags musl -a -installsuffix cgo -o main .

EXPOSE 9000
EXPOSE 40000

CMD ["dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "--continue=true", "exec", "./main"]